prefix=`date --rfc-3339=date`;
post_file="$HOME/workspace/amirr0r.github.io/_posts/$prefix-.md";
echo "---" > $post_file;
echo "title: " >> $post_file;
echo "date: `date --rfc-3339=seconds | cut -d'+' -f1` +0100" >> $post_file;
echo "categories: []" >> $post_file;
echo "tags: []" >> $post_file;
echo "image: " >> $post_file;
echo "---" >> $post_file;
# code $post_file;